openapi: 3.0.1
info:
  title: Partner Opportunities
  description: "<br><br>**Purpose of the API**<br><br>The API is for partners to retrieve\
    \ **'opportunities'** relevant to optimizing their book of business. Opportunities\
    \ are actionable insights for partners that drive value to advertisers.<br><br>For\
    \ a step by step guide to using our API, we recommend our official [developer\
    \ guide](https://advertising.amazon.com/API/docs/en-us/guides/recommendations/partner-opportunities/overview).<br><br>**How\
    \ should partners use this set of APIs?**<br><br>Partners should use this set\
    \ of APIs by first calling the **GET** `/partnerOpportunities` route to obtain\
    \ a list of opportunities that are pertinent (and exclusive) to their book of\
    \ business (the advertisers they manage).<br><br>It should be noted that the opportunities\
    \ returned in this list call may not have data for that day (opportunities are\
    \ updated every 24 hours). To check if an opportunity has data, introspect on\
    \ the value of the `opportunities[].dataMetadata.rowCount` field. If the value\
    \ is greater than zero, data is available and a data file can be downloaded.<br><br>Once\
    \ an opportunity of interest has been identified, the given opportunity data can\
    \ be downloaded using the **GET** `/partnerOpportunities/{partnerOpportunityId}/file`\
    \ route, which will redirect to a pre-signed file download URL containing all\
    \ opportunity data in a CSV format. This operation will return a 404 if no data\
    \ is available for the given opportunity.<br><br>Partners can get aggregated information\
    \ about opportunities available to them using the **GET** `/partnerOpportunities/summary`\
    \ route. This information includes total opportunity count, count of opportunities\
    \ with data available to be downloaded, and a count of unique advertisers across\
    \ all opportunities. <br><br>**Required Headers**<br><br>Currently, there are\
    \ two headers that are required for all API calls. If these headers are not correctly\
    \ provided and properly formatted, the API call requests will fail.<br><br>1.\
    \ `Accept:` Must be set to a supported API version (see below), using the format\
    \ described on the [Advertising API portal](https://advertising.amazon.com/API/docs/en-us/concepts/compatibility-versioning-policy).\
    \ The request and response payloads are identical between versions v1, v1.1, and\
    \ v1.2.<br>    - Version 1 (Recommended): `'application/vnd.partneropportunity.v1+json'`<br>\
    \    - Version 1.1: `'application/vnd.partneropportunity.v1.1+json'`<br>    -\
    \ Version 1.2: `'application/vnd.partneropportunity.v1.2+json'`<br>  <br>2. `Amazon-Advertising-API-Manager-Account:`\
    \ 'Partner Network Account ID' which is accessible from Partner Network under\
    \ the ['User settings'](https://advertising.amazon.com/partner-network/settings)\
    \ link in the upper right corner.<br>    - Example: `'amzn1.ads1.ma1.abcd1234...'`<br><br>**Applying\
    \ Opportunities**<br>Partners can take action against opportunities based on their\
    \ business needs. For example, partners may choose to use existing Advertising\
    \ API resources to launch new ASINs or modify campaign settings. Some entries\
    \ in your opportunity data file will have `recommendationId`s and `applyApiEndPoint`s.\
    \ These opportunities will have objective type `AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS`\
    \ and can be supplied back to the `/apply` endpoint to programmatically take action\
    \ on each opportunity.<br><br>See [How to use the Partner Opportunities API](https://advertising.amazon.com/API/docs/en-us/guides/recommendations/partner-opportunities/how-to)\
    \ for additional details. <br><br>**Advanced Usage**<br><br>**Pagination**<br><br>The\
    \ `/partnerOpportunities` route supports pagination of results via query parameters.\
    \ <br><br>**GET** `/partnerOpportunities` calls support using *optional* query\
    \ parameters `maxResults` and `nextToken` for paginated requests and responses.\
    \ <br>**GET** `/partnerOpportunities` responses include tokens which can be used\
    \ to navigate to the first, previous, next, and last pages of results. To navigate\
    \ to the desired page, pass one of these provided tokens as a query parameter\
    \ for the next call to **GET** `/partnerOpportunities`.<br><br>Examples:<br>-\
    \ **GET** `/partnerOpportunities?maxResults=10` will return 10 opportunities and\
    \ a valid series of pagination tokens.<br>- **GET** `/partnerOpportunities?maxResults=10&nextToken=[next-page-token]`\
    \ will get the next 10 opportunities. <br><br>**Filtering**<br><br>The `/partnerOpportunities`\
    \ and `/partnerOpportunities/summary` routes support filtering results via query\
    \ parameters.<br><br>**GET** `/partnerOpportunities` calls support using *optional*\
    \ query parameters `audience`, `objectiveType`, `product`, `advertiserId`, and\
    \ `profileId` for filtering responses.<br>**GET** `/partnerOpportunities` responses\
    \ will include only opportunities which have values matching the requested filters.\
    \ If no filters are specified, all opportunities are returned.<br><br>Examples:<br>-\
    \ **GET** `/partnerOpportunities?objectiveType=UNLAUNCHED_ASINS&product=AMAZON_DSP,SPONSORED_PRODUCTS`\
    \ will return all opportunities which have a `objectiveType` of `UNLAUNCHED_ASINS`\
    \ and a `product` of `AMAZON_DSP` OR `SPONSORED_PRODUCTS`.<br>- **GET** `/partnerOpportunities?advertiserId=A12345,B67890`\
    \ will return all opportunities that contain data for `advertiserId` `A12345`\
    \ OR `B67890`.<br>- **GET** `/partnerOpportunities?profileId=12345,67890` will\
    \ return all opportunities that contain data for `profileId` `12345` OR `67890`.<br>-\
    \ **GET** `/partnerOpportunities?advertiserId=A12345,B67890&profileId=12345,67890`\
    \ will return all opportunities that contain data for `advertiserId` `A12345`\
    \ OR `B67890` OR `profileId` `12345` OR `67890`.<br><br>**GET** `/partnerOpportunities/summary`\
    \ calls support using *optional* query parameters `audience`, `objectiveType`,\
    \ and `product` for filtering responses.<br>**GET** `/partnerOpportunities/summary`\
    \ responses will include metadata for the filter values for opportunities under\
    \ the `availableAudiences`, `availableObjectiveTypes`, etc. fields. This metadata\
    \ will include the available filter values along with the number of opportunities\
    \ for those filter values.<br><br>Examples:<br>- **GET** `/partnerOpportunities/summary?product=SPONSORED_PRODUCTS`\
    \ will provide a summary of all opportunities that have a `product` value of `SPONSORED_PRODUCTS`.<br><br>**Localization**<br><br>The\
    \ `/partnerOpportunities` route supports a `locale` query parameter for retrieving\
    \ opportunities in a localized manner.<br><br>**GET** `/partnerOpportunities`\
    \ calls support the *optional* query parameter `locale` for localizing responses.<br>**GET**\
    \ `/partnerOpportunities` responses will be localized to the requested `locale`\
    \ if possible and filtered out if not.<br><br>Example:<br>- **GET** `/partnerOpportunities?locale=zh_CN`\
    \ to request opportunity responses localized in Chinese.<br><br>**Additional Resources**<br><br>For\
    \ more information on **CURL** command formatting, please see [the Amazon Ads\
    \ Website](https://advertising.amazon.com/API/docs/en-us/getting-started/first-call).<br>"
  version: "3.0"
servers:
- url: /
paths:
  /partnerOpportunities:
    get:
      tags:
      - Partner Opportunities
      summary: ""
      description: |-
        Gets a list of opportunities specific to the partner making the request.

        **Authorized resource type**:
        Global Manager Account ID

        **Parameter name**:
        Amazon-Advertising-API-Manager-Account

        **Parameter in**:
        header

        **Requires one of these permissions**:
        ["MasterAccount_Manager","MasterAccount_Viewer","ManagerAccount_Dev","MA_ReadOnly"]
      operationId: partnerOpportunitiesListOpportunities
      parameters:
      - name: maxResults
        in: query
        description: The maximum number of results to return in a single page.
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          minimum: 1
          type: number
        example: "10"
      - name: nextToken
        in: query
        description: An obfuscated cursor value that indicates which 'page' of results
          should be returned next.
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: asdf1234
      - name: locale
        in: query
        description: "The desired locale for opportunity data to be presented in.\
          \ The `title`, `description`, and `callToAction` fields of the response\
          \ items support localization."
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Locale'
        example: en_US
      - name: retrieveTranslationKeys
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: advertiserId
        in: query
        description: Filter for opportunities using advertiserId. Each advertiserId
          must be fewer than 50 characters.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 100
          minItems: 1
          type: array
          items:
            type: string
        example: A12345BCD6789E
      - name: profileId
        in: query
        description: Filter for opportunities using profileId. Each profileId must
          be fewer than 50 characters.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 100
          minItems: 1
          type: array
          items:
            type: number
        example: "1234567890"
      - name: audience
        in: query
        description: |-
          Filter for opportunities with these audience values.
          * PARTNER_MANAGED_ADVERTISERS - Recommendation relates to advertisers the partner manages.
          * PARTNER_MANAGED_AD_BUSINESS - Recommendation relates to other partners the partner interacts with.
          * PARTNER - Recommendation relates to you, the partner.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 3
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - PARTNER
            - PARTNER_MANAGED_ADVERTISERS
            - PARTNER_MANAGED_AD_BUSINESS
        example: PARTNER
      - name: objectiveType
        in: query
        description: |
          Filter for opportunities with these objectiveType values.
          * AD_API_ENDPOINT_ADOPTION - Recommendation relates to adopting a new API endpoint.
          * ADVERTISER_INSIGHTS - Recommendation relates to advertiser insights.
          * AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS - Recommendation is provided by the Amazon Ads Account Team.
          * BENCHMARKING_INSIGHTS - Recommendation relates to performance insights comparing against similar partners, brands, campaigns, or ASINs.
          * CAMPAIGN_OPTIMIZATION - Recommendation relates to optimizing campaigns.
          * CATEGORY_INSIGHTS - Recommendation relates to advertising insights across product categories..
          * CLICK_CREDITS - Recommendation relates to available click credits.
          * DEALS - Recommendation relates to deals.
          * MARKETPLACE_EXPANSION - Recommendation relates to expanding to new marketplaces.
          * NEW_TO_BRAND_INSIGHTS - Recommendation relates to new to brand advertising insights.
          * PARTNER_GROWTH - Recommendation relates to growing your business as a partner.
          * PATH_TO_PURCHASE_INSIGHTS - Recommendation relates to path to purchase insights.
          * READY_TO_LAUNCH_CAMPAIGNS - Recommendation relates to ready to launch campaigns.
          * RETAIL_INSIGHTS - Recommendation related to retail insights about products you manage.
          * SHARE_OF_VOICE_INSIGHTS - Recommendation relates to share of voice for a particular audience.
          * UNLAUNCHED_ASINS - Recommendation relates to ASINs you manage that are not enrolled in advertising campaigns.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 16
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - ADVERTISER_INSIGHTS
            - AD_API_ENDPOINT_ADOPTION
            - AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS
            - BENCHMARKING_INSIGHTS
            - CAMPAIGN_OPTIMIZATION
            - CATEGORY_INSIGHTS
            - CLICK_CREDITS
            - DEALS
            - MARKETPLACE_EXPANSION
            - NEW_TO_BRAND_INSIGHTS
            - PARTNER_GROWTH
            - PATH_TO_PURCHASE_INSIGHTS
            - READY_TO_LAUNCH_CAMPAIGNS
            - RETAIL_INSIGHTS
            - SHARE_OF_VOICE_INSIGHTS
            - UNLAUNCHED_ASINS
        example: DEALS
      - name: product
        in: query
        description: |-
          Filter for opportunities with these product values.
          * AMAZON_DSP - Recommendation relates to the Amazon DSP.
          * AMAZON_LIVE - Recommendation relates to Amazon's Live Show and Tell program.
          * CROSS_PRODUCT - Recommendation relates to multiple Amazon Ads products including leveraging insights between products
          * POSTS - Deprecated
          * SPONSORED_BRANDS - Recommendation relates to Sponsored Brands.
          * SPONSORED_BRANDS_VIDEO - Recommendation relates to Sponsored Brands Video.
          * SPONSORED_DISPLAY - Recommendation relates to Sponsored Display.
          * SPONSORED_DISPLAY_VIDEO - Recommendation relates to Sponsored Display Video.
          * SPONSORED_PRODUCTS - Recommendation relates to Sponsored Products.
          * SPONSORED_TV - Recommendation relates to Sponsored TV.
          * STORES - Recommendation relates to building a storefront page on Amazon.
          * VIDEO_ADS - Deprecated value, replaced by SPONSORED_BRANDS_VIDEO and SPONSORED_DISPLAY_VIDEO values.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 12
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - AMAZON_DSP
            - AMAZON_LIVE
            - CROSS_PRODUCT
            - POSTS
            - SPONSORED_BRANDS
            - SPONSORED_BRANDS_VIDEO
            - SPONSORED_DISPLAY
            - SPONSORED_DISPLAY_VIDEO
            - SPONSORED_PRODUCTS
            - SPONSORED_TV
            - STORES
            - VIDEO_ADS
        example: SPONSORED_PRODUCTS
      - name: Amazon-Advertising-API-ClientId
        in: header
        description: The identifier of a client associated with a 'Login with Amazon'
          account.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-Manager-Account
        in: header
        description: "'Partner Network Account ID' which is accessible from Partner\
          \ Network under the ['User settings'](https://advertising.amazon.com/partner-network/settings)\
          \ link in the upper right corner."
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: A list of opportunities successfully retrieved.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesOpportunitiesPageV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesOpportunitiesPageV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesOpportunitiesPageV1'
  /partnerOpportunities/summary:
    get:
      tags:
      - Partner Opportunities
      summary: ""
      description: |-
        Gets aggregated information about all opportunities specific to the partner making the request. Supported since V1.1.

        **Authorized resource type**:
        Global Manager Account ID

        **Parameter name**:
        Amazon-Advertising-API-Manager-Account

        **Parameter in**:
        header

        **Requires one of these permissions**:
        ["MasterAccount_Manager","MasterAccount_Viewer","ManagerAccount_Dev","MA_ReadOnly"]
      operationId: partnerOpportunitiesSummarizeOpportunities
      parameters:
      - name: audience
        in: query
        description: |-
          Filter for opportunities with these audience values.
          * PARTNER_MANAGED_ADVERTISERS - Recommendation relates to advertisers the partner manages.
          * PARTNER_MANAGED_AD_BUSINESS - Recommendation relates to other partners the partner interacts with.
          * PARTNER - Recommendation relates to you, the partner.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 3
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - PARTNER
            - PARTNER_MANAGED_ADVERTISERS
            - PARTNER_MANAGED_AD_BUSINESS
        example: PARTNER
      - name: objectiveType
        in: query
        description: |
          Filter for opportunities with these objectiveType values.
          * AD_API_ENDPOINT_ADOPTION - Recommendation relates to adopting a new API endpoint.
          * ADVERTISER_INSIGHTS - Recommendation relates to advertiser insights.
          * AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS - Recommendation is provided by the Amazon Ads Account Team.
          * BENCHMARKING_INSIGHTS - Recommendation relates to performance insights comparing against similar partners, brands, campaigns, or ASINs.
          * CAMPAIGN_OPTIMIZATION - Recommendation relates to optimizing campaigns.
          * CATEGORY_INSIGHTS - Recommendation relates to advertising insights across product categories..
          * CLICK_CREDITS - Recommendation relates to available click credits.
          * DEALS - Recommendation relates to deals.
          * MARKETPLACE_EXPANSION - Recommendation relates to expanding to new marketplaces.
          * NEW_TO_BRAND_INSIGHTS - Recommendation relates to new to brand advertising insights.
          * PARTNER_GROWTH - Recommendation relates to growing your business as a partner.
          * PATH_TO_PURCHASE_INSIGHTS - Recommendation relates to path to purchase insights.
          * READY_TO_LAUNCH_CAMPAIGNS - Recommendation relates to ready to launch campaigns.
          * RETAIL_INSIGHTS - Recommendation related to retail insights about products you manage.
          * SHARE_OF_VOICE_INSIGHTS - Recommendation relates to share of voice for a particular audience.
          * UNLAUNCHED_ASINS - Recommendation relates to ASINs you manage that are not enrolled in advertising campaigns.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 16
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - ADVERTISER_INSIGHTS
            - AD_API_ENDPOINT_ADOPTION
            - AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS
            - BENCHMARKING_INSIGHTS
            - CAMPAIGN_OPTIMIZATION
            - CATEGORY_INSIGHTS
            - CLICK_CREDITS
            - DEALS
            - MARKETPLACE_EXPANSION
            - NEW_TO_BRAND_INSIGHTS
            - PARTNER_GROWTH
            - PATH_TO_PURCHASE_INSIGHTS
            - READY_TO_LAUNCH_CAMPAIGNS
            - RETAIL_INSIGHTS
            - SHARE_OF_VOICE_INSIGHTS
            - UNLAUNCHED_ASINS
        example: DEALS
      - name: product
        in: query
        description: |-
          Filter for opportunities with these product values.
          * AMAZON_DSP - Recommendation relates to the Amazon DSP.
          * AMAZON_LIVE - Recommendation relates to Amazon's Live Show and Tell program.
          * CROSS_PRODUCT - Recommendation relates to multiple Amazon Ads products including leveraging insights between products
          * POSTS - Deprecated
          * SPONSORED_BRANDS - Recommendation relates to Sponsored Brands.
          * SPONSORED_BRANDS_VIDEO - Recommendation relates to Sponsored Brands Video.
          * SPONSORED_DISPLAY - Recommendation relates to Sponsored Display.
          * SPONSORED_DISPLAY_VIDEO - Recommendation relates to Sponsored Display Video.
          * SPONSORED_PRODUCTS - Recommendation relates to Sponsored Products.
          * SPONSORED_TV - Recommendation relates to Sponsored TV.
          * STORES - Recommendation relates to building a storefront page on Amazon.
          * VIDEO_ADS - Deprecated value, replaced by SPONSORED_BRANDS_VIDEO and SPONSORED_DISPLAY_VIDEO values.
        required: false
        style: form
        explode: true
        schema:
          maxItems: 12
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - AMAZON_DSP
            - AMAZON_LIVE
            - CROSS_PRODUCT
            - POSTS
            - SPONSORED_BRANDS
            - SPONSORED_BRANDS_VIDEO
            - SPONSORED_DISPLAY
            - SPONSORED_DISPLAY_VIDEO
            - SPONSORED_PRODUCTS
            - SPONSORED_TV
            - STORES
            - VIDEO_ADS
        example: SPONSORED_PRODUCTS
      - name: Amazon-Advertising-API-ClientId
        in: header
        description: The identifier of a client associated with a 'Login with Amazon'
          account.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-Manager-Account
        in: header
        description: "'Partner Network Account ID' which is accessible from Partner\
          \ Network under the ['User settings'](https://advertising.amazon.com/partner-network/settings)\
          \ link in the upper right corner."
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Information about per-partner opportunity data.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesOpportunitiesSummaryV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesOpportunitiesSummaryV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesOpportunitiesSummaryV1'
  /partnerOpportunities/{partnerOpportunityId}/applicationStatus:
    post:
      tags:
      - Partner Opportunities
      summary: ""
      description: |-
        Retrieves the current status of applied recommendations.

        **Authorized resource type**:
        Global Manager Account ID

        **Parameter name**:
        Amazon-Advertising-API-Manager-Account

        **Parameter in**:
        header

        **Requires one of these permissions**:
        ["MasterAccount_Manager","MasterAccount_Viewer","ManagerAccount_Dev","MA_ReadOnly"]
      operationId: partnerOpportunitiesApplicationStatus
      parameters:
      - name: partnerOpportunityId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-ClientId
        in: header
        description: The identifier of a client associated with a 'Login with Amazon'
          account.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-Manager-Account
        in: header
        description: "'Partner Network Account ID' which is accessible from Partner\
          \ Network under the ['User settings'](https://advertising.amazon.com/partner-network/settings)\
          \ link in the upper right corner."
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/vnd.partneropportunity.v1+json:
            schema:
              $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusRequestDtoV1'
          application/vnd.partneropportunity.v1.1+json:
            schema:
              $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusRequestDtoV1'
          application/vnd.partneropportunity.v1.2+json:
            schema:
              $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusRequestDtoV1'
        required: true
      responses:
        "200":
          description: Returns a JSON payload with a list of recommendations and their
            corresponding status.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusResponseDtoV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusResponseDtoV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusResponseDtoV1'
        "400":
          description: Bad request - check that all provided request data matches
            what is provided in your opportunity file and try again.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusErrorDtoV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusErrorDtoV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusErrorDtoV1'
        "401":
          description: "Unauthorized - please double check your authentication headers\
            \ and be sure to follow our [getting started guide](https://advertising.amazon.com/API/docs/en-us/guides/recommendations/partner-opportunities/getting-started#authorization)"
        "429":
          description: Too many requests - Request was denied due to request throttling.
            Please try again later.
        "500":
          description: Internal Server Error - we have been notified of the error
            and are taking action to see the issue rectified. Please try again later.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusErrorDtoV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusErrorDtoV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatusErrorDtoV1'
  /partnerOpportunities/{partnerOpportunityId}/apply:
    post:
      tags:
      - Partner Opportunities
      summary: ""
      description: |-
        Applies a given set of recommendations. Application may be asynchronous. Application status may be checked using the applicationStatus operation. Note that all required parameters are retrieved from opportunity data.

        **Authorized resource type**:
        Global Manager Account ID

        **Parameter name**:
        Amazon-Advertising-API-Manager-Account

        **Parameter in**:
        header

        **Requires one of these permissions**:
        ["MasterAccount_Manager","MasterAccount_Viewer","ManagerAccount_Dev","MA_ReadOnly"]
      operationId: partnerOpportunitiesApply
      parameters:
      - name: partnerOpportunityId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-ClientId
        in: header
        description: The identifier of a client associated with a 'Login with Amazon'
          account.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-Manager-Account
        in: header
        description: "'Partner Network Account ID' which is accessible from Partner\
          \ Network under the ['User settings'](https://advertising.amazon.com/partner-network/settings)\
          \ link in the upper right corner."
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/vnd.partneropportunity.v1+json:
            schema:
              $ref: '#/components/schemas/PartnerOpportunitiesApplyRequestDtoV1'
          application/vnd.partneropportunity.v1.1+json:
            schema:
              $ref: '#/components/schemas/PartnerOpportunitiesApplyRequestDtoV1'
          application/vnd.partneropportunity.v1.2+json:
            schema:
              $ref: '#/components/schemas/PartnerOpportunitiesApplyRequestDtoV1'
        required: true
      responses:
        "202":
          description: Returns a 202 to indicate that all recommendations were accepted
            and will be processed over time.
        "400":
          description: Bad request - check that all provided request data matches
            what is provided in your opportunity file and try again.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
        "401":
          description: "Unauthorized - please double check your authentication headers\
            \ and be sure to follow our [getting started guide](https://advertising.amazon.com/API/docs/en-us/guides/recommendations/partner-opportunities/getting-started#authorization)"
        "422":
          description: Unprocessable Content - some or all of the provided recommendation
            IDs failed to apply. See the response body for more information.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
        "429":
          description: Too many requests - Request was denied due to request throttling.
            Please try again later.
        "500":
          description: Internal Server Error - we have been notified of the error
            and are taking action to see the issue rectified. Please try again later.
          content:
            application/vnd.partneropportunity.v1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
            application/vnd.partneropportunity.v1.1+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
            application/vnd.partneropportunity.v1.2+json:
              schema:
                $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorDtoV1'
  /partnerOpportunities/{partnerOpportunityId}/file:
    get:
      tags:
      - Partner Opportunities
      summary: ""
      description: |-
        Gets a 307 - TEMPORARY_REDIRECT to an opportunity data file.

        **Authorized resource type**:
        Global Manager Account ID

        **Parameter name**:
        Amazon-Advertising-API-Manager-Account

        **Parameter in**:
        header

        **Requires one of these permissions**:
        ["MasterAccount_Manager","MasterAccount_Viewer","ManagerAccount_Dev","MA_ReadOnly"]
      operationId: partnerOpportunitiesGetOpportunityFile
      parameters:
      - name: partnerOpportunityId
        in: path
        description: The opportunity ID for which the file URL is desired.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: fileFormat
        in: query
        description: Specify the desired file format for the opportunity data. Default
          is CSV.
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: CSV
          enum:
          - CSV
          - GZIP_JSON
        example: CSV
      - name: Amazon-Advertising-API-ClientId
        in: header
        description: The identifier of a client associated with a 'Login with Amazon'
          account.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-Manager-Account
        in: header
        description: "'Partner Network Account ID' which is accessible from Partner\
          \ Network under the ['User settings'](https://advertising.amazon.com/partner-network/settings)\
          \ link in the upper right corner."
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: "This response will never occur. Redirects will always happen\
            \ instead, but OpenAPI requires a 200 response spec."
        "307":
          description: Redirect URL provided in Location header.
          headers:
            Location:
              description: The header containing the pre-signed URL (expires in 15
                minutes) to which the browser/user agent will be redirected in order
                to complete the file download.
              style: simple
              explode: false
              schema:
                type: string
        "404":
          description: Not Found - The requested partnerOpportunityId has no available
            data file or the file is empty.
components:
  schemas:
    Locale:
      type: string
      enum:
      - ar_AE
      - cs_CZ
      - de_DE
      - en_AU
      - en_CA
      - en_GB
      - en_IN
      - en_SG
      - en_US
      - es_CO
      - es_ES
      - es_MX
      - es_US
      - fr_CA
      - fr_FR
      - he_IL
      - hi_IN
      - it_IT
      - ja_JP
      - ko_KR
      - nl_NL
      - pl_PL
      - pt_BR
      - sv_SE
      - ta_IN
      - th_TH
      - tr_TR
      - vi_VN
      - zh_CN
      - zh_TW
    PartnerOpportunitiesApplicationMarketplace:
      type: string
      description: |-
        Plain text marketplace value.

        Provided in opportunity data.
      enum:
      - AE
      - AU
      - BR
      - CA
      - DE
      - EG
      - ES
      - FR
      - GB
      - IN
      - IT
      - JP
      - MX
      - NL
      - PL
      - SA
      - SE
      - SG
      - TR
      - UK
      - US
    PartnerOpportunitiesApplicationStatus:
      required:
      - campaignId
      - recommendationId
      - status
      type: object
      properties:
        campaignId:
          type: string
        recommendationId:
          type: string
        status:
          type: string
          enum:
          - FAILED
          - IN_PROGRESS
          - PUBLISHED
          - REJECTED
          - SUCCESS
      example:
        campaignId: campaignId
        recommendationId: recommendationId
        status: FAILED
    PartnerOpportunitiesApplicationStatusErrorDtoV1:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          enum:
          - PO_APPLICATION_STATUS_BAD_REQUEST
          - PO_APPLICATION_STATUS_INTERNAL_SERVER_ERROR
        message:
          type: string
    PartnerOpportunitiesApplicationStatusRequestDtoV1:
      required:
      - advertiserType
      - encryptedAdvertiserId
      - entityId
      - marketplace
      - recommendationIds
      type: object
      properties:
        advertiserType:
          type: string
          description: |-
            Entity Type

            Provided in opportunity data as 'advertiserType'.
          example: SELLER
          enum:
          - SELLER
          - VENDOR
        encryptedAdvertiserId:
          type: string
          description: |-
            The encrypted advertiser ID.

            Provided in opportunity data.
          example: A1234ABC890
        entityId:
          type: string
          description: |-
            Entity ID

            Provided in opportunity data.
          example: ENTITY1234
        marketplace:
          $ref: '#/components/schemas/PartnerOpportunitiesApplicationMarketplace'
        recommendationIds:
          maxItems: 500
          minItems: 1
          type: array
          description: |-
            A list of recommendation IDs for which status will be retrieved.

            Provided in opportunity data.
          example:
          - 50644397-f143-4375-b907-ffd2c20a076d
          - 94ea8af3-36cb-4792-abcf-034db46bbce0
          items:
            type: string
    PartnerOpportunitiesApplicationStatusResponseDtoV1:
      required:
      - statuses
      type: object
      properties:
        statuses:
          maxItems: 500
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesApplicationStatus'
      example:
        statuses:
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
        - campaignId: campaignId
          recommendationId: recommendationId
          status: FAILED
    PartnerOpportunitiesApplyErrorDtoV1:
      required:
      - code
      - failures
      - message
      - successes
      type: object
      properties:
        code:
          type: string
          enum:
          - PO_APPLY_ALREADY_APPLIED
          - PO_APPLY_BAD_REQUEST
          - PO_APPLY_INTERNAL_SERVER_ERROR
          - PO_APPLY_IN_TERMINAL_STATUS
          - PO_APPLY_UNPROCESSABLE_ERROR
        failures:
          maxItems: 100
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorFailures'
        message:
          type: string
        successes:
          maxItems: 100
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesApplyErrorSuccesses'
    PartnerOpportunitiesApplyErrorFailures:
      required:
      - code
      - message
      - recommendationId
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        recommendationId:
          type: string
    PartnerOpportunitiesApplyErrorSuccesses:
      required:
      - recommendationId
      type: object
      properties:
        recommendationId:
          type: string
    PartnerOpportunitiesApplyRequestDtoV1:
      required:
      - advertiserType
      - encryptedAdvertiserId
      - entityId
      - marketplace
      - recommendationIds
      type: object
      properties:
        advertiserType:
          type: string
          description: |-
            Entity Type

            Provided in opportunity data as 'advertiserType'.
          example: SELLER
          enum:
          - SELLER
          - VENDOR
        encryptedAdvertiserId:
          type: string
          description: |-
            The encrypted advertiser ID.

            Provided in opportunity data.
          example: A1234ABC890
        entityId:
          type: string
          description: |-
            Entity ID

            Provided in opportunity data.
          example: ENTITY1234
        marketplace:
          $ref: '#/components/schemas/PartnerOpportunitiesApplicationMarketplace'
        recommendationIds:
          maxItems: 100
          minItems: 1
          type: array
          description: A list of recommendation IDs to apply for the given opportunity.
          example:
          - 50644397-f143-4375-b907-ffd2c20a076d
          - 94ea8af3-36cb-4792-abcf-034db46bbce0
          items:
            type: string
    PartnerOpportunitiesOpportunitiesPageV1:
      required:
      - opportunities
      - totalResults
      type: object
      properties:
        firstToken:
          type: string
          description: Pagination token back to the first page/element.
        lastToken:
          type: string
          description: Pagination token to the last page.
        nextToken:
          type: string
          description: Pagination token to the next page.
        opportunities:
          maxItems: 100
          minItems: 1
          type: array
          description: The list of partner opportunities.
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesOpportunityV1'
        prevToken:
          type: string
          description: Pagination token back to the previous page.
        totalResults:
          type: number
          description: Total results contained in the list of opportunities.
      example:
        lastToken: lastToken
        totalResults: 0.8008281904610115
        firstToken: firstToken
        nextToken: nextToken
        opportunities:
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        - dataMetadata: ""
          dataUrl: dataUrl
          audience: PARTNER
          product: AMAZON_DSP
          createdDate: 2000-01-23T04:56:07.000+00:00
          description: description
          updatedDate: 2000-01-23T04:56:07.000+00:00
          title: title
          objectiveType: ADVERTISER_INSIGHTS
          callToAction: callToAction
          objective: AWARENESS
          partnerOpportunityId: partnerOpportunityId
        prevToken: prevToken
    PartnerOpportunitiesOpportunitiesSummaryV1:
      required:
      - availableAudiences
      - availableObjectiveTypes
      - availableProducts
      - opportunitiesCount
      - opportunitiesWithDataCount
      - uniqueAdvertiserApproximateCount
      type: object
      properties:
        availableAudiences:
          maxItems: 3
          minItems: 3
          type: array
          description: All available opportunity audience values with the number of
            opportunities for each.
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesOpportunityAudienceFilterSummaryV1'
        availableObjectiveTypes:
          maxItems: 12
          minItems: 12
          type: array
          description: All available opportunity objective values with the number
            of opportunities for each.
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesOpportunityObjectiveTypeFilterSummaryV1'
        availableProducts:
          maxItems: 10
          minItems: 10
          type: array
          description: All available opportunity product values with the number of
            opportunities for each.
          items:
            $ref: '#/components/schemas/PartnerOpportunitiesOpportunityProductFilterSummaryV1'
        opportunitiesCount:
          type: number
          description: Total number of opportunities for the partner.
        opportunitiesWithDataCount:
          type: number
          description: Number of actionable opportunities with data for the partner.
        uniqueAdvertiserApproximateCount:
          type: number
          description: Approximate number of unique advertisers across all opportunities
            for the partner.
      example:
        uniqueAdvertiserApproximateCount: 2.3021358869347655
        availableProducts:
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        - count: 1.4658129805029452
          value: AMAZON_DSP
        opportunitiesCount: 5.962133916683182
        opportunitiesWithDataCount: 5.637376656633329
        availableAudiences:
        - count: 0.8008281904610115
          value: PARTNER
        - count: 0.8008281904610115
          value: PARTNER
        - count: 0.8008281904610115
          value: PARTNER
        availableObjectiveTypes:
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
        - count: 6.027456183070403
          value: ADVERTISER_INSIGHTS
    PartnerOpportunitiesOpportunityAudienceFilterSummaryV1:
      required:
      - count
      - value
      type: object
      properties:
        count:
          type: number
        value:
          type: string
          enum:
          - PARTNER
          - PARTNER_MANAGED_ADVERTISERS
          - PARTNER_MANAGED_AD_BUSINESS
      example:
        count: 0.8008281904610115
        value: PARTNER
    PartnerOpportunitiesOpportunityDataMetadataV1:
      required:
      - rowCount
      - updatedDate
      type: object
      properties:
        rowCount:
          type: number
          description: Number of rows present in the latest partner opportunity data
            file.
        updatedDate:
          type: string
          description: "Date the opportunity data file was generated/updated, in ISO\
            \ 8601 format."
          format: date-time
    PartnerOpportunitiesOpportunityObjectiveTypeFilterSummaryV1:
      required:
      - count
      - value
      type: object
      properties:
        count:
          type: number
        value:
          type: string
          enum:
          - ADVERTISER_INSIGHTS
          - AD_API_ENDPOINT_ADOPTION
          - AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS
          - BENCHMARKING_INSIGHTS
          - CAMPAIGN_OPTIMIZATION
          - CATEGORY_INSIGHTS
          - CLICK_CREDITS
          - DEALS
          - MARKETPLACE_EXPANSION
          - NEW_TO_BRAND_INSIGHTS
          - PARTNER_GROWTH
          - PATH_TO_PURCHASE_INSIGHTS
          - READY_TO_LAUNCH_CAMPAIGNS
          - RETAIL_INSIGHTS
          - SHARE_OF_VOICE_INSIGHTS
          - UNLAUNCHED_ASINS
      example:
        count: 6.027456183070403
        value: ADVERTISER_INSIGHTS
    PartnerOpportunitiesOpportunityProductFilterSummaryV1:
      required:
      - count
      - value
      type: object
      properties:
        count:
          type: number
        value:
          type: string
          enum:
          - AMAZON_DSP
          - AMAZON_LIVE
          - CROSS_PRODUCT
          - POSTS
          - SPONSORED_BRANDS
          - SPONSORED_BRANDS_VIDEO
          - SPONSORED_DISPLAY
          - SPONSORED_DISPLAY_VIDEO
          - SPONSORED_PRODUCTS
          - SPONSORED_TV
          - STORES
          - VIDEO_ADS
      example:
        count: 1.4658129805029452
        value: AMAZON_DSP
    PartnerOpportunitiesOpportunityV1:
      required:
      - audience
      - callToAction
      - createdDate
      - dataMetadata
      - dataUrl
      - description
      - objectiveType
      - partnerOpportunityId
      - product
      - title
      - updatedDate
      type: object
      properties:
        audience:
          type: string
          description: "The intended audience of the opportunity. For example, it\
            \ might be targeted towards optimizing partner metrics or the metrics\
            \ of advertisers that the partner manages."
          enum:
          - PARTNER
          - PARTNER_MANAGED_ADVERTISERS
          - PARTNER_MANAGED_AD_BUSINESS
        callToAction:
          type: string
          description: An explanation of why it's recommended to take the actions
            detailed in the opportunity's data file.
        createdDate:
          type: string
          description: "When the opportunity was created, in ISO 8601 format. This\
            \ should never change."
          format: date-time
        dataMetadata:
          description: |-
            Contains the most recent data file information for the opportunity.

            Can be used to track the availability of a partner opportunity data file:
               if dataMetadata.rowCount > 0.
          allOf:
          - $ref: '#/components/schemas/PartnerOpportunitiesOpportunityDataMetadataV1'
        dataUrl:
          type: string
          description: |-
            The URL through which an opportunity's data file (in CSV format) can be downloaded.

            A simple GET request is all that is necessary, which will automatically redirect to a presigned, short-lived URL.

            URLs expire in 15 minutes.
        description:
          type: string
          description: A detailed description of the opportunity and how it is pertinent
            to partners. May provide a summary of the underlying data provided in
            the opportunity data file.
        objective:
          type: string
          description: |-
            The objective of the opportunity. For example, an objective might be to drive sales, raise brand awareness, etc.

            Deprecated.
          enum:
          - AWARENESS
          - BRAND_ENGAGEMENT
          - RETENTION
          - SALES
        objectiveType:
          type: string
          description: "The objective type of the opportunity. For example, an objective\
            \ type might be around providing the unlaunched ASINs you can optimize\
            \ or deals you can action on."
          enum:
          - ADVERTISER_INSIGHTS
          - AD_API_ENDPOINT_ADOPTION
          - AMAZON_ACCOUNT_TEAM_RECOMMENDATIONS
          - BENCHMARKING_INSIGHTS
          - CAMPAIGN_OPTIMIZATION
          - CATEGORY_INSIGHTS
          - CLICK_CREDITS
          - DEALS
          - MARKETPLACE_EXPANSION
          - NEW_TO_BRAND_INSIGHTS
          - PARTNER_GROWTH
          - PATH_TO_PURCHASE_INSIGHTS
          - READY_TO_LAUNCH_CAMPAIGNS
          - RETAIL_INSIGHTS
          - SHARE_OF_VOICE_INSIGHTS
          - UNLAUNCHED_ASINS
        partnerOpportunityId:
          type: string
          description: The unique ID for the opportunity.
        product:
          type: string
          description: "The Amazon Advertising product to which the opportunity corresponds,\
            \ like Amazon DSP, Video Ads, etc."
          enum:
          - AMAZON_DSP
          - AMAZON_LIVE
          - CROSS_PRODUCT
          - POSTS
          - SPONSORED_BRANDS
          - SPONSORED_BRANDS_VIDEO
          - SPONSORED_DISPLAY
          - SPONSORED_DISPLAY_VIDEO
          - SPONSORED_PRODUCTS
          - SPONSORED_TV
          - STORES
          - VIDEO_ADS
        title:
          type: string
          description: The title of the opportunity.
        updatedDate:
          type: string
          description: "When the opportunity was last updated, in ISO 8601 format."
          format: date-time
      example:
        dataMetadata: ""
        dataUrl: dataUrl
        audience: PARTNER
        product: AMAZON_DSP
        createdDate: 2000-01-23T04:56:07.000+00:00
        description: description
        updatedDate: 2000-01-23T04:56:07.000+00:00
        title: title
        objectiveType: ADVERTISER_INSIGHTS
        callToAction: callToAction
        objective: AWARENESS
        partnerOpportunityId: partnerOpportunityId
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
