openapi: 3.0.1
info:
  title: Product Selector
  description: "The Amazon Product Selector API allows integrators to receive product\
    \ metadata such as inventory status, price, eligibility status and product details\
    \ for SKUS or ASINs in their Product Catalog in order to launch, manage or optimize\
    \ Sponsored Product, Sponsored Brands or Sponsored Display advertising campaigns.\
    \ The Product Selector API is available to Sellers, Vendors, and Authors. Note\
    \ that for vendors it fetches inventory based on the vendor codes so the result\
    \ could be different from elsewhere."
  version: "3.0"
servers:
- url: /
paths:
  /product/metadata:
    post:
      tags:
      - Product Selector
      summary: Returns product metadata for the advertiser
      description: |2-


        **Authorized resource type**:
        DSP Rodeo Entity ID, DSP Advertiser Account ID

        **Parameter name**:
        Amazon-Ads-AccountId

        **Parameter in**:
        header

        **Requires one of these permissions**:
        ["advertiser_campaign_edit","advertiser_campaign_view","campaign_edit","campaign_view"]
      operationId: ProductMetadata
      parameters:
      - name: Amazon-Advertising-API-ClientId
        in: header
        description: The identifier of a client associated with a "Login with Amazon"
          account.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Advertising-API-Scope
        in: header
        description: The identifier of a profile associated with the advertiser account.
          Use `GET` method on Profiles resource to list profiles associated with the
          access token passed in the HTTP Authorization header and choose profile
          id `profileId` from the response to pass it as input.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: Amazon-Ads-AccountId
        in: header
        description: Account identifier you use to access the DSP. This is your Amazon
          DSP Advertiser ID.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/vnd.productmetadatarequest.v1+json:
            schema:
              $ref: '#/components/schemas/ProductMetadataRequest'
        required: true
      responses:
        "200":
          description: Successful operation.
          content:
            application/vnd.productmetadataresponse.v1+json:
              schema:
                $ref: '#/components/schemas/ProductMetadataResponse'
        "400":
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        "401":
          description: Unauthenticated request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        "403":
          description: Forbidden - Request failed because user is not authorized to
            access a resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        "404":
          description: Not Found - Requested resource does not exist or is not visible
            for the authenticated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        "429":
          description: Too Many Requests - Request was rate-limited. Retry later.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    ProductMetadataModel:
      type: object
      properties:
        asin:
          type: string
          description: ASIN of the item
          example: B0018OFKJS
        availability:
          type: string
          description: "Stock availability: \n * IN_STOCK - The item is in stock.\
            \ \n * IN_STOCK_SCARCE - The item is in stock, but stock levels are limited.\
            \ \n * OUT_OF_STOCK - The item is currently out of stock. \n * PREORDER\
            \ - The item is not yet available, but can be pre-ordered. \n * LEADTIME\
            \ - The item is only available after some amount of lead time. \n * AVAILABLE_DATE\
            \ - The item is not available, but will be available on a future date."
          example: IN_STOCK
        basisPrice:
          $ref: '#/components/schemas/basisPrice'
        bestSellerRank:
          type: string
          description: Best seller rank position in the category
          example: "36"
        brand:
          type: string
          description: Brand name of the item
          example: Levi's
        category:
          type: string
          description: Category (browse node) name of the ASIN
          example: Men's Jeans
        createdDate:
          type: string
          description: Date the item was first available on Amazon
          example: "Jul 1, 2021"
        eligibilityStatus:
          type: string
          description: "Eligibility status for advertising: \n * ELIGIBLE - Eligible\
            \ for advertising \n * INELIGIBLE - Ineligible for advertising"
          example: ELIGIBLE
        globalStoreSetting:
          $ref: '#/components/schemas/ProductMetadataModel_globalStoreSetting'
        imageUrl:
          type: string
          description: Url to the product image
          example: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
        ineligibilityCodes:
          maxItems: 12
          minItems: 0
          type: array
          description: List of ineligible status identifier
          example:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          items:
            type: string
        ineligibilityReasons:
          maxItems: 12
          minItems: 0
          type: array
          description: List of reasons that made this item ineligible to be advertised
          example:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
          items:
            type: string
        priceToPay:
          $ref: '#/components/schemas/priceToPay'
        sku:
          type: string
          description: sku of the item
          example: SKU1
        title:
          type: string
          description: Product title of the item
          example: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
        variationList:
          maxItems: 1500
          minItems: 0
          type: array
          description: List of ASIN variations of the current item
          example:
          - ASIN_XL_size
          - ASIN_blue_color
          items:
            type: string
      example:
        priceToPay:
          amount: 3.99
          currency: USD
        ineligibilityCodes:
        - INELIGIBLE_CONDITION
        - MISSING_TITLE
        availability: IN_STOCK
        title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
        eligibilityStatus: ELIGIBLE
        basisPrice:
          amount: 6.99
          currency: USD
        globalStoreSetting:
          catalogSourceCountryCode: US
        bestSellerRank: "36"
        createdDate: "Jul 1, 2021"
        imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
        asin: B0018OFKJS
        category: Men's Jeans
        sku: SKU1
        brand: Levi's
        variationList:
        - ASIN_XL_size
        - ASIN_blue_color
        ineligibilityReasons:
        - This product is missing basic information to be advertised
        - This product is unsafe to be advertised
    ProductMetadataRequest:
      required:
      - pageIndex
      - pageSize
      type: object
      properties:
        adType:
          type: string
          description: "Program type. Required if checks advertising eligibility:\
            \ \n * SP - Sponsored Product \n * SB - Sponsored Brand \n * SD - Sponsored\
            \ Display"
          enum:
          - SB
          - SD
          - SP
        asins:
          maxItems: 300
          minItems: 0
          type: array
          description: Specific asins to search for in the advertiser's inventory.
            Cannot use together with skus or searchStr input types.
          example:
          - B0018OFKJS
          - B01IR7S432
          items:
            maxLength: 10
            minLength: 10
            type: string
        checkEligibility:
          type: boolean
          description: Whether advertising eligibility info is required
          default: false
        checkItemDetails:
          type: boolean
          description: "Whether item details such as name, image, and price is required."
          default: false
        cursorToken:
          type: string
          description: Pagination token used for the suggested sort type or for author
            merchant
        isGlobalStoreSelection:
          type: boolean
          description: " This will return only GlobalStore listings related to [GlobalStore\
            \ Program](https://sellercentral.amazon.com/help/hub/reference/external/202139180)\
            \ and not local listings"
          default: false
        locale:
          type: string
          description: Optional locale for detail and eligibility response strings.
            Default to the marketplace locale.
          example: zh_CN
        pageIndex:
          minimum: 0
          type: integer
          description: "Index of the page to be returned; For author, this value will\
            \ be ignored, should use cursorToken instead. For seller and vendor, results\
            \ are capped at 10k ((pageIndex + 1) * pageSize)."
          format: int32
          example: 0
        pageSize:
          maximum: 300
          minimum: 1
          type: integer
          description: Number of items to be returned on this page index.
          format: int32
          example: 5
        searchStr:
          maxLength: 200
          type: string
          description: Specific string in the item title to search for in the advertiser's
            inventory. Case insensitive. Cannot use together with asins or skus input
            types.
          example: jean
        skus:
          maxItems: 300
          minItems: 0
          type: array
          description: Specific SKUs to search for in the advertiser's inventory.
            Currently only support SP program type for sellers. Cannot use together
            with asins or searchStr input types.
          example:
          - sku1
          - sku2
          items:
            type: string
        sortBy:
          type: string
          description: "Sort option for the result. Currently only support SP program\
            \ type for sellers: \n * SUGGESTED - Suggested products are those most\
            \ likely to engage customers, and have a higher chance of generating clicks\
            \ if advertised. \n * CREATED_DATE - Date the item listing was created "
          enum:
          - CREATED_DATE
          - SUGGESTED
        sortOrder:
          type: string
          description: "Sort order (has to be DESC for the suggested sort type): \n\
            \ * ASC - Ascending, from A to Z \n * DESC - Descending, from Z to A"
          default: DESC
          enum:
          - ASC
          - DESC
    ProductMetadataResponse:
      type: object
      properties:
        ProductMetadataList:
          maxItems: 300
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/ProductMetadataModel'
        cursorToken:
          type: string
          description: Pagination token for later requests with specific sort type
            to use as the page index instead. Empty cursorToken means no further data
            is present at Server side.
      example:
        cursorToken: cursorToken
        ProductMetadataList:
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
        - priceToPay:
            amount: 3.99
            currency: USD
          ineligibilityCodes:
          - INELIGIBLE_CONDITION
          - MISSING_TITLE
          availability: IN_STOCK
          title: Wrangler Men's Classic 5-Pocket Regular Fit Flex Jean
          eligibilityStatus: ELIGIBLE
          basisPrice:
            amount: 6.99
            currency: USD
          globalStoreSetting:
            catalogSourceCountryCode: US
          bestSellerRank: "36"
          createdDate: "Jul 1, 2021"
          imageUrl: https://m.media-amazon.com/images/I/51s3ut4zPxL._SS60_.jpg
          asin: B0018OFKJS
          category: Men's Jeans
          sku: SKU1
          brand: Levi's
          variationList:
          - ASIN_XL_size
          - ASIN_blue_color
          ineligibilityReasons:
          - This product is missing basic information to be advertised
          - This product is unsafe to be advertised
    basisPrice:
      type: object
      properties:
        amount:
          type: number
          description: Price amount
          example: 6.99
        currency:
          type: string
          description: Currency of the price
          example: USD
      description: The basis price before the savings are calculated
      example:
        amount: 6.99
        currency: USD
    error:
      type: object
      properties:
        code:
          type: string
          description: Enumerated error type.
        details:
          type: string
          description: A human-readable description of the response.
      description: Error response object.
    priceToPay:
      type: object
      properties:
        amount:
          type: number
          description: Price amount
          example: 3.99
        currency:
          type: string
          description: Currency of the price
          example: USD
      description: The price customer would pay for the buying option
      example:
        amount: 3.99
        currency: USD
    ProductMetadataModel_globalStoreSetting:
      type: object
      properties:
        catalogSourceCountryCode:
          maxLength: 2
          minLength: 2
          type: string
          description: "Country code of source marketplace where seller has listed\
            \ the product. Possible source country codes include US, UK, DE, JP, and\
            \ AE."
          example: US
      description: "This denotes the fields related to [GlobalStore Program](https://sellercentral.amazon.com/help/hub/reference/external/202139180)."
      example:
        catalogSourceCountryCode: US
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
